<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JIP9vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jI__P9v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jI__P9v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'participationEvent' => ['privates', '.errored..service_locator.jI__P9v.App\\Entity\\ParticipationEvent', NULL, 'Cannot autowire service ".service_locator.jI__P9v": it references class "App\\Entity\\ParticipationEvent" but no such service exists.'],
        ], [
            'participationEvent' => 'App\\Entity\\ParticipationEvent',
        ]);
    }
}
