<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YwCA3HPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YwCA3HP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YwCA3HP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'gouvernoratRepository' => ['privates', 'App\\Repository\\GouvernoratRepository', 'getGouvernoratRepositoryService', true],
        ], [
            'gouvernoratRepository' => 'App\\Repository\\GouvernoratRepository',
        ]);
    }
}
