<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VBIKq1lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VBIKq1l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VBIKq1l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'gouvernoratRepository' => ['privates', 'App\\Repository\\GouvernoratRepository', 'getGouvernoratRepositoryService', true],
        ], [
            'entityManager' => '?',
            'gouvernoratRepository' => 'App\\Repository\\GouvernoratRepository',
        ]);
    }
}
