<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PlET1EJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PlET1EJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PlET1EJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'participationEvent' => ['privates', '.errored..service_locator.PlET1EJ.App\\Entity\\ParticipationEvent', NULL, 'Cannot autowire service ".service_locator.PlET1EJ": it references class "App\\Entity\\ParticipationEvent" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'participationEvent' => 'App\\Entity\\ParticipationEvent',
        ]);
    }
}
