<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getActivities3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.qJVB7RL.App\Entity\Activities' shared service.
     *
     * @return \App\Entity\Activities
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.qJVB7RL": it references class "App\\Entity\\Activities" but no such service exists.');
    }
}
