<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipationActivityService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.NIvFPFx.App\Entity\ParticipationActivity' shared service.
     *
     * @return \App\Entity\ParticipationActivity
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.NIvFPFx": it references class "App\\Entity\\ParticipationActivity" but no such service exists.');
    }
}
