<?php

namespace ContainerLZQrKLA;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRateHotelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.7YN8FCi.App\Entity\RateHotel' shared service.
     *
     * @return \App\Entity\RateHotel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.7YN8FCi": it references class "App\\Entity\\RateHotel" but no such service exists.');
    }
}
