<?php

namespace ContainerWKHoKoL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_STnIZBtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.STnIZBt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.STnIZBt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activity' => ['privates', '.errored..service_locator.STnIZBt.App\\Entity\\Activities', NULL, 'Cannot autowire service ".service_locator.STnIZBt": it references class "App\\Entity\\Activities" but no such service exists.'],
        ], [
            'activity' => 'App\\Entity\\Activities',
        ]);
    }
}
