<?php

namespace ContainerYntd5w4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CqqlKhqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CqqlKhq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CqqlKhq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'hotel' => ['privates', '.errored..service_locator.CqqlKhq.App\\Entity\\Hotel', NULL, 'Cannot autowire service ".service_locator.CqqlKhq": it references class "App\\Entity\\Hotel" but no such service exists.'],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'hotel' => 'App\\Entity\\Hotel',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'userRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
