<?php

namespace ContainerYntd5w4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NGXXRejService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NGXXRej' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NGXXRej'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'activity' => ['privates', '.errored..service_locator.NGXXRej.App\\Entity\\Activities', NULL, 'Cannot autowire service ".service_locator.NGXXRej": it references class "App\\Entity\\Activities" but no such service exists.'],
            'participationRepository' => ['privates', 'App\\Repository\\ParticipationActivityRepository', 'getParticipationActivityRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService', true],
        ], [
            'activity' => 'App\\Entity\\Activities',
            'participationRepository' => 'App\\Repository\\ParticipationActivityRepository',
            'userRepository' => 'App\\Repository\\UtilisateurRepository',
        ]);
    }
}
