<?php

namespace ContainerYntd5w4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7YN8FCiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7YN8FCi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7YN8FCi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'rateHotel' => ['privates', '.errored..service_locator.7YN8FCi.App\\Entity\\RateHotel', NULL, 'Cannot autowire service ".service_locator.7YN8FCi": it references class "App\\Entity\\RateHotel" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'rateHotel' => 'App\\Entity\\RateHotel',
        ]);
    }
}
