<?php

namespace ContainerYntd5w4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGouvernorat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uXv2U7b.App\Entity\Gouvernorat' shared service.
     *
     * @return \App\Entity\Gouvernorat
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.uXv2U7b": it references class "App\\Entity\\Gouvernorat" but no such service exists.');
    }
}
