<?php

namespace ContainerYntd5w4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipationEventService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PlET1EJ.App\Entity\ParticipationEvent' shared service.
     *
     * @return \App\Entity\ParticipationEvent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.PlET1EJ": it references class "App\\Entity\\ParticipationEvent" but no such service exists.');
    }
}
