<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5WF22cv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5WF22cv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5WF22cv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5WF22cv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5WF22cv\App_KernelDevDebugContainer([
    'container.build_hash' => '5WF22cv',
    'container.build_id' => '2cd35a12',
    'container.build_time' => 1682972719,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5WF22cv');
