<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYntd5w4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYntd5w4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYntd5w4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYntd5w4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYntd5w4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yntd5w4',
    'container.build_id' => 'b6e86450',
    'container.build_time' => 1682298579,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYntd5w4');
